kind: Application

micronaut:
  application:
    name: postManage
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
  
  datasources:
    default:
      url: jdbc:postgresql://localhost:5432/auth_db
      username: postgres
      password: yourpassword
      driver-class-name: org.postgresql.Driver
  
  http:
    client:
      json-types:
        - application/json
        - text/plain
        - application/octet-stream

socialMediaUploader:
  - name: instagram
    credentials:
      userName: userName
      password: password
      clientId: clientId
  - name: facebook
    credentials:
      userName: userName
      password: password
      clientId: clientId

platforms:
  enabled:
    - INSTAGRAM
    - FACEBOOK