micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
datasources:
  default:
    url: jdbc:h2:file:./data/userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;INIT=runscript from 'classpath:schema.sql';
    driver-class-name: org.h2.Driver
    username: admin
    password: "admin"
    dialect: H2
    schema-generate: CREATE_DROP

  
  http:
    client:
      json-types:
        - application/json
        - text/plain
        - application/octet-stream
  server:
    cors:
      enabled: true
      configurations:
        frontend:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - Accept
          exposed-headers:
            - Content-Type
            - Authorization
          max-age: 1800

socialMediaUploader:
  - name: instagram
    credentials:
      userName: userName
      password: password
      clientId: clientId
  - name: facebook
    credentials:
      userName: userName
      password: password
      clientId: clientId

platforms:
  enabled:
    - INSTAGRAM
    - FACEBOOK