

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    mobile VARCHAR(11),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);


ALTER TABLE customer ADD COLUMN IF NOT EXISTS user_limit INT NOT NULL;
