


CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    mobile VARCHAR(11),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_limit INT NOT NULL DEFAULT 10
);

